version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: btc-db
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: always
    volumes:
      - ~/.containers/db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
