version: '3.7'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    container_name: btc-keycloak-db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - '~/.containers/keycloak:/bitnami/postgresql:z'

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    container_name: btc-keycloak
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_DATABASE_HOST: btc-keycloak-db
    depends_on:
      - postgresql
